const { CatchErrorHandler } = require("../middlewares/CatchErrorHandler")

//this is only use for syncronous code

// exports.homeComponent = (req,res,next)=>{
//     res.json({message: "Welcome to the component"})
// }

// for async code we use try catch

// exports.homeComponentAsync = async (req,res,next)=>{
//     try {
//         res.json({message: "Welcome to the component"})
//     } catch (error) {
//         res.json(error)
//     }
// }

// because of very much routes and use of try catch multiple times we use another middleware to prevent writing the code multiple times

exports.homeComponent = CatchErrorHandler(async(req,res,next)=>{
    res.json({message: "Welcome to the component"})
})